### ISSUE TITLE
Use pipe character for first line in a multi line string

### ISSUE THREAD

**Issue by hseeberger** [britter/diamond-kata-scala#1]
This makes it easier to digest the shape of the string.

See https://github.com/britter/diamond-kata-scala/blob/master/src/test/scala/de/britter/diamondkata/DiamondGeneratorTest.scala#L38`:

``` scala
"""| A  // added the pipe here!
   |B B
   | A """.stripMargin
```

**Comment by britter** [comment]
Thank you! Unfortunately IntelliJ doesn't insert that automatically :-(
